### ISSUE TITLE
Is there a method for getting query results as an array?

### ISSUE THREAD

**Issue by nurbek-ab** [mardix/VoodOrm#3]
Hello! Consider the following statement:
`$user_ids = $db->users()->select('user_id');`
Now I want to use array_map on $user_ids and I know I cannot, because it's an object. How can I get the array of query results from that object?

**Comment by mardix** [comment]
Hey @nurbek-ab 

The method VoodOrm::find() is used to execute a select query. By default, it will return an ArrayIterator of VoodOrm object for each rows. 

Also, VoodOrm::find(Closure $callback) accepts a callback function in which the the all the rows are passed in as array. This way, you can do much more powerful data manipulation.

So to answer your question, to get the list of the ids, you can do it this way:

```
$user_ids = $db->users()->find(function($rows){
                    $ids = [];
                    foreach ($rows as $row) {
                        $ids[] = $row[$id];
                    }
                    return $ids;
                });
```

Or to return the results as array

```
$users_array = $db->users()->find(function($rows){
                    return $rows;
                });
```

Both results will return a native PHP array instead of VoodOrm object
